# Generated by Django 4.1.3 on 2022-11-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=32)),
                ('due', models.DateTimeField()),
                ('priority', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('difficulty', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=32)),
                ('visible', models.CharField(max_length=32)),
            ],
        ),
    ]
