# Generated by Django 4.1.3 on 2022-11-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssistantApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
